# ~/.config/kitty/kitty.conf

# Tipografía para íconos de DevOps
font_family      JetBrainsMono Nerd Font
font_size        12.0

# Forzar el uso de Zsh
shell            zsh
# Estética Monocromática
background            #0a0a0a
foreground            #d0d0d0
cursor                #ffffff
selection_background  #333333
selection_foreground  #ffffff

# Colores (Todo en escala de grises para no romper la estética)
color0  #222222
color8  #444444
color1  #555555
color9  #777777
color2  #888888
color10 #aaaaaa
color3  #bbbbbb
color11 #cccccc
color4  #dddddd
color12 #eeeeee
color5  #666666
color13 #999999
color6  #333333
color14 #555555
color7  #ffffff
color15 #ffffff

# Transparencia (Opcional, 1.0 es opaco)
background_opacity 0.95

# Rendimiento
repaint_delay 10
input_delay 3
sync_to_monitor yes
